CREATE TABLE PENGGUNA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	EMAIL VARCHAR(255),
	FIRST_NAME VARCHAR(255),
	LAST_NAME VARCHAR(255),
	PASSWORD VARCHAR(255),
	PROFILE_IMAGE VARCHAR(255),
	TOKEN VARCHAR(255)
);

INSERT INTO PENGGUNA (ID, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PROFILE_IMAGE) VALUES (1, 'dhaniradeamalia@gmail.com', 'Dhanira', 'Amalia', 'nutech123', 'https://dhaniraapi.com/profile.jpeg');

CREATE TABLE BANNER(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	BANNER_NAME VARCHAR(255),
	BANNER_IMG VARCHAR(255),
	BANNER_DSCP VARCHAR(255),
);

INSERT INTO BANNER (ID, BANNER_NAME, BANNER_IMG, BANNER_DSCP) VALUES (1, 'Banner 1', 'https://nutech-integrasi.app/dummy.jpg', 'Lerem Ipsum Dolor sit amet');
INSERT INTO BANNER (ID, BANNER_NAME, BANNER_IMG, BANNER_DSCP) VALUES (2, 'Banner 2', 'https://nutech-integrasi.app/dummy.jpg', 'Lerem Ipsum Dolor sit amet');
INSERT INTO BANNER (ID, BANNER_NAME, BANNER_IMG, BANNER_DSCP) VALUES (3, 'Banner 3', 'https://nutech-integrasi.app/dummy.jpg', 'Lerem Ipsum Dolor sit amet');
INSERT INTO BANNER (ID, BANNER_NAME, BANNER_IMG, BANNER_DSCP) VALUES (4, 'Banner 4', 'https://nutech-integrasi.app/dummy.jpg', 'Lerem Ipsum Dolor sit amet');
INSERT INTO BANNER (ID, BANNER_NAME, BANNER_IMG, BANNER_DSCP) VALUES (5, 'Banner 5', 'https://nutech-integrasi.app/dummy.jpg', 'Lerem Ipsum Dolor sit amet');
INSERT INTO BANNER (ID, BANNER_NAME, BANNER_IMG, BANNER_DSCP) VALUES (6, 'Banner 6', 'https://nutech-integrasi.app/dummy.jpg', 'Lerem Ipsum Dolor sit amet');

CREATE TABLE LAYANAN(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	SERVICE_CODE VARCHAR(255),
	SERVICE_NAME VARCHAR(255),
	SERVICE_ICON VARCHAR(255),
	TARIFF INT
);

INSERT INTO LAYANAN (ID, SERVICE_CODE, SERVICE_NAME, SERVICE_ICON, TARIFF) VALUES (1, 'PAJAK', 'Pajak PBB', 'https://nutech-integrasi.app/dummy.jpg', 40000);
INSERT INTO LAYANAN (ID, SERVICE_CODE, SERVICE_NAME, SERVICE_ICON, TARIFF) VALUES (2, 'PLN', 'Listrik', 'https://nutech-integrasi.app/dummy.jpg', 10000);
INSERT INTO LAYANAN (ID, SERVICE_CODE, SERVICE_NAME, SERVICE_ICON, TARIFF) VALUES (3, 'PDAM', 'PDAM Berlangganan', 'https://nutech-integrasi.app/dummy.jpg', 40000);
INSERT INTO LAYANAN (ID, SERVICE_CODE, SERVICE_NAME, SERVICE_ICON, TARIFF) VALUES (4, 'PULSA', 'Pulsa', 'https://nutech-integrasi.app/dummy.jpg', 40000);
INSERT INTO LAYANAN (ID, SERVICE_CODE, SERVICE_NAME, SERVICE_ICON, TARIFF) VALUES (5, 'PGN', 'PGN Berlangganan', 'https://nutech-integrasi.app/dummy.jpg', 50000);
INSERT INTO LAYANAN (ID, SERVICE_CODE, SERVICE_NAME, SERVICE_ICON, TARIFF) VALUES (6, 'MUSIK', 'Musik Berlangganan', 'https://nutech-integrasi.app/dummy.jpg', 50000);
INSERT INTO LAYANAN (ID, SERVICE_CODE, SERVICE_NAME, SERVICE_ICON, TARIFF) VALUES (7, 'TV', 'TV Berlangganan', 'https://nutech-integrasi.app/dummy.jpg', 50000);
INSERT INTO LAYANAN (ID, SERVICE_CODE, SERVICE_NAME, SERVICE_ICON, TARIFF) VALUES (8, 'PAKET_DATA', 'Paket data', 'https://nutech-integrasi.app/dummy.jpg', 50000);
INSERT INTO LAYANAN (ID, SERVICE_CODE, SERVICE_NAME, SERVICE_ICON, TARIFF) VALUES (9, 'VOUCHER_GAME', 'Voucher Game', 'https://nutech-integrasi.app/dummy.jpg', 100000);
INSERT INTO LAYANAN (ID, SERVICE_CODE, SERVICE_NAME, SERVICE_ICON, TARIFF) VALUES (10, 'VOUCHER_MAKANAN', 'Voucher makanan', 'https://nutech-integrasi.app/dummy.jpg', 100000);
INSERT INTO LAYANAN (ID, SERVICE_CODE, SERVICE_NAME, SERVICE_ICON, TARIFF) VALUES (11, 'QURBAN', 'Qurban', 'https://nutech-integrasi.app/dummy.jpg', 200000);
INSERT INTO LAYANAN (ID, SERVICE_CODE, SERVICE_NAME, SERVICE_ICON, TARIFF) VALUES (12, 'ZAKAT', 'Zakat', 'https://nutech-integrasi.app/dummy.jpg', 300000);

CREATE TABLE ACCT_BALANCE(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	USER_ID INT NOT NULL,
	BALANCE DECIMAL(15,2) DEFAULT 0.00,
	FOREIGN KEY (USER_ID) REFERENCES PENGGUNA(ID) ON DELETE CASCADE
);

INSERT INTO ACCT_BALANCE (ID, USER_ID, BALANCE) VALUES (1, 1, 100000.00);
INSERT INTO ACCT_BALANCE (ID, USER_ID, BALANCE) VALUES (2, 4, 200000.00);
INSERT INTO ACCT_BALANCE (ID, USER_ID, BALANCE) VALUES (3, 8, 300000.00);

CREATE TABLE TRX_HISTORY(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	INVOICE_NUMBER VARCHAR(255),
	TRX_TYPE VARCHAR(255),
	DESCRIPTION VARCHAR(255),
	TOTAL_AMOUNT INT,
	DT_CREATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO TRX_HISTORY (ID, INVOICE_NUMBER, TRX_TYPE, DESCRIPTION, TOTAL_AMOUNT, DT_CREATE) VALUES (1, 'INV17082023-001', 'TOPUP', 'Top Up balance', 100000 , '2023-08-17 10:10:10.000');
INSERT INTO TRX_HISTORY (ID, INVOICE_NUMBER, TRX_TYPE, DESCRIPTION, TOTAL_AMOUNT, DT_CREATE) VALUES (2, 'INV17082023-002', 'PAYMENT', 'PLN Pascabayar', 100000 , '2023-08-17 11:10:10.000');
INSERT INTO TRX_HISTORY (ID, INVOICE_NUMBER, TRX_TYPE, DESCRIPTION, TOTAL_AMOUNT, DT_CREATE) VALUES (3, 'INV17082023-003', 'PAYMENT', 'Pulsa Indosat', 400000 , '2023-08-17 10:10:10.000');